# Generated by Django 3.2.5 on 2021-10-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10, verbose_name='Day')),
                ('start', models.CharField(choices=[('8', '8'), ('8:30', '8:30'), ('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30'), ('13', '13'), ('13:30', '13:30'), ('14', '14'), ('14:30', '14:30'), ('15', '15'), ('15:30', '15:30'), ('16', '16'), ('16:30', '16:30'), ('17', '17'), ('17:30', '17:30'), ('18', '18'), ('18:30', '18:30'), ('19', '19'), ('19:30', '19:30'), ('20', '20'), ('20:30', '20:30'), ('21', '21'), ('21:30', '21:30')], max_length=5, verbose_name='Start')),
                ('end', models.CharField(choices=[('8', '8'), ('8:30', '8:30'), ('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30'), ('13', '13'), ('13:30', '13:30'), ('14', '14'), ('14:30', '14:30'), ('15', '15'), ('15:30', '15:30'), ('16', '16'), ('16:30', '16:30'), ('17', '17'), ('17:30', '17:30'), ('18', '18'), ('18:30', '18:30'), ('19', '19'), ('19:30', '19:30'), ('20', '20'), ('20:30', '20:30'), ('21', '21'), ('21:30', '21:30')], max_length=5, verbose_name='End')),
            ],
        ),
    ]
