# Generated by Django 3.2.5 on 2021-10-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], max_length=10, verbose_name='Day'),
        ),
    ]
