# Generated by Django 3.2.5 on 2021-10-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0002_auto_20211025_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.SmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.SmallIntegerField(choices=[(1, '8'), (2, '8:30'), (3, '9'), (4, '9:30'), (5, '10'), (6, '10:30'), (7, '11'), (8, '11:30'), (9, '12'), (10, '12:30'), (11, '13'), (12, '13:30'), (13, '14'), (14, '14:30'), (15, '15'), (16, '15:30'), (17, '16'), (18, '16:30'), (19, '17'), (20, '17:30'), (21, '18'), (22, '18:30'), (23, '19'), (24, '19:30'), (25, '20'), (26, '20:30'), (27, '21'), (28, '21:30')], verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.SmallIntegerField(choices=[(1, '8'), (2, '8:30'), (3, '9'), (4, '9:30'), (5, '10'), (6, '10:30'), (7, '11'), (8, '11:30'), (9, '12'), (10, '12:30'), (11, '13'), (12, '13:30'), (13, '14'), (14, '14:30'), (15, '15'), (16, '15:30'), (17, '16'), (18, '16:30'), (19, '17'), (20, '17:30'), (21, '18'), (22, '18:30'), (23, '19'), (24, '19:30'), (25, '20'), (26, '20:30'), (27, '21'), (28, '21:30')], verbose_name='Start'),
        ),
    ]
