# Generated by Django 3.2.5 on 2021-10-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0003_auto_20211025_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.SmallIntegerField(blank=True, verbose_name='Order'),
        ),
    ]
