# Generated by Django 3.2.5 on 2021-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0004_alter_schedule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
