# Generated by Django 3.2.5 on 2022-01-06 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la publicacion')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID publicacion')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Codigo de la publicacion')),
                ('numberOfVisites', models.PositiveIntegerField(default=0, verbose_name='Numero de visitas')),
                ('shortLink', models.URLField(blank=True, verbose_name='Enlace corto')),
                ('longLink', models.URLField(blank=True, verbose_name='Enlace largo')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
