# Generated by Django 3.2.11 on 2023-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe una publicación con este nombre.'}, max_length=50, unique=True, verbose_name='Publicacion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('code', models.PositiveIntegerField(blank=True, verbose_name='Code')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('shorten_link', models.BooleanField(default=True, verbose_name='Acortar link')),
                ('short_link', models.URLField(blank=True, null=True, verbose_name='Link corto')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['code'], name='publication_code_560169_idx'),
        ),
    ]
