# Generated by Django 4.0 on 2022-01-06 11:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='longLink',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='shortLink',
            new_name='short_link',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='numberOfVisites',
            new_name='visits',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='uuid',
        ),
        migrations.AddField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID publicacion'),
        ),
    ]
