# Generated by Django 3.2.5 on 2022-01-06 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Publicacion'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link corto'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
    ]
