# Generated by Django 4.0 on 2022-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20220106_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='uuid',
        ),
        migrations.AddField(
            model_name='publication',
            name='shorted_link',
            field=models.BooleanField(default=True, verbose_name='Acortar link'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='code',
            field=models.PositiveIntegerField(blank=True, verbose_name='Code'),
        ),
    ]
