# Generated by Django 4.0 on 2022-01-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publication_uuid_publication_shorted_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='shorted_link',
            new_name='shorten_link',
        ),
    ]
