# Generated by Django 3.2.5 on 2022-01-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_rename_shorted_link_publication_shorten_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['code'], name='publication_code_560169_idx'),
        ),
    ]
