# Generated by Django 3.2.5 on 2022-01-08 17:40

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
                ('num_products', models.PositiveSmallIntegerField(verbose_name='Number of products')),
                ('enable', models.BooleanField(default=False, verbose_name='Enable')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Product code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('normalized_name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('stock', models.SmallIntegerField(null=True, verbose_name='Cantidad disponible')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('vendor_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Vendor code')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brands')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('img', models.ImageField(null=True, upload_to=products.models.upload_img, verbose_name='Image')),
                ('img_webp', models.ImageField(null=True, upload_to=products.models.upload_img_webp, verbose_name='Image WEBP')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('categories', models.ManyToManyField(to='products.Category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='product_code_idx'),
        ),
    ]
