# Generated by Django 3.2.5 on 2022-01-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_250',
            field=models.ImageField(blank=True, null=True, upload_to='img/250', verbose_name='Image 250'),
        ),
    ]
