# Generated by Django 3.2.5 on 2022-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
