# Generated by Django 3.2.5 on 2022-01-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img_250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_250',
        ),
        migrations.AddField(
            model_name='product',
            name='img_270',
            field=models.ImageField(blank=True, null=True, upload_to='img/270', verbose_name='Image 270 px'),
        ),
    ]
