# Generated by Django 3.2.5 on 2022-01-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brands',
            new_name='brand_name',
        ),
    ]
