# Generated by Django 3.2.5 on 2022-01-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_brands_product_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
