# Generated by Django 3.2.5 on 2022-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_imageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='load_img',
            field=models.BooleanField(default=False, verbose_name='Load img'),
        ),
    ]
