# Generated by Django 3.2.5 on 2022-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_products',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Number of products'),
            preserve_default=False,
        ),
    ]
