# Generated by Django 3.2.5 on 2022-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_num_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Vendor code'),
        ),
    ]
