# Generated by Django 3.2.5 on 2022-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveSmallIntegerField(max_length=20, verbose_name='Product code'),
        ),
    ]
