# Generated by Django 3.2.5 on 2022-01-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220118_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProduct',
        ),
    ]
