# Generated by Django 3.2.5 on 2022-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='Enable'),
        ),
    ]
