# Generated by Django 3.2.11 on 2023-05-12 07:12

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230511_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to=products.models.upload_img_product),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_small',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_small_webp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_webp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
