# Generated by Django 3.2.11 on 2023-05-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230512_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_small',
        ),
    ]
