# Generated by Django 3.2.11 on 2023-10-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_category_enable_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_code_4c2607_idx',
        ),
    ]
