# Generated by Django 3.2.5 on 2022-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
