# Generated by Django 3.2.5 on 2022-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_log', '0004_auto_20220108_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
