# Generated by Django 3.2.5 on 2022-01-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage_log', '0005_auto_20220108_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlog',
            options={'verbose_name': 'Producto consultado', 'verbose_name_plural': 'Productos consultos'},
        ),
    ]
