# Generated by Django 3.2.5 on 2021-10-23 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=50, verbose_name='Consulta realizada')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='SearchWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=50, verbose_name='Texto')),
                ('typeString', models.CharField(max_length=1, verbose_name='Tipo de texto')),
                ('idObject', models.IntegerField(verbose_name='Id de object')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Contador de cantidades de consultas')),
                ('priority', models.BooleanField(default=False, verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Item consultado',
                'verbose_name_plural': 'Items consultados',
                'ordering': ['-priority', '-quantity'],
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='ID de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UseOfCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad de consultas')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Uso de categoria',
                'verbose_name_plural': 'Uso de categorias',
                'ordering': ['-quantity'],
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la publicacion')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID publicacion')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Codigo de la publicacion')),
                ('numberOfVisites', models.PositiveIntegerField(default=0, verbose_name='Numero de visitas')),
                ('shortLink', models.URLField(blank=True, verbose_name='Enlace corto')),
                ('longLink', models.URLField(blank=True, verbose_name='Enlace largo')),
                ('products', models.ManyToManyField(to='products.Product')),
                ('users', models.ManyToManyField(to='user_information.UserInformation')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='ProductsOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.PositiveIntegerField(verbose_name='Id de producto de interes')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad de visualizaciones')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_information.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='DateOfVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha visita')),
                ('lastPage', models.URLField(null=True, verbose_name='Pagina de la que proviene')),
                ('browser', models.CharField(max_length=20, null=True, verbose_name='Navegador')),
                ('versionBrowser', models.CharField(max_length=5, null=True, verbose_name='Version del Navegador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_information.userinformation')),
            ],
        ),
    ]
