# Generated by Django 3.2.5 on 2022-01-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
