# Generated by Django 3.2.5 on 2022-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Phone')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Contact date')),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact List',
                'ordering': ['-date'],
            },
        ),
    ]
