# Generated by Django 3.2.11 on 2023-04-27 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Format: +549999999999 o 549999999999 up to 16 digits.', regex='^\\+?\\d{9,16}$')], verbose_name='Phone')),
            ],
        ),
    ]
