# Generated by Django 3.2.11 on 2023-04-30 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20230428_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Format: +549999999999 o 549999999999 up to 16 digits.', regex='^\\+?\\d{9,16}$')], verbose_name='Phone'),
        ),
    ]
