# Generated by Django 3.2.11 on 2023-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactinformation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='address',
            field=models.CharField(default='Katzenbachstrasse 225, Zurich', max_length=100),
            preserve_default=False,
        ),
    ]
