# Generated by Django 3.2.11 on 2023-06-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['uuid'], name='chat_uuid_idx'),
        ),
    ]
