# Generated by Django 3.2.11 on 2024-04-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdocument',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
