# Generated by Django 3.2.5 on 2022-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Day')),
                ('start', models.SmallIntegerField(choices=[(1, '8'), (2, '8:30'), (3, '9'), (4, '9:30'), (5, '10'), (6, '10:30'), (7, '11'), (8, '11:30'), (9, '12'), (10, '12:30'), (11, '13'), (12, '13:30'), (13, '14'), (14, '14:30'), (15, '15'), (16, '15:30'), (17, '16'), (18, '16:30'), (19, '17'), (20, '17:30'), (21, '18'), (22, '18:30'), (23, '19'), (24, '19:30'), (25, '20'), (26, '20:30'), (27, '21'), (28, '21:30')], verbose_name='Start')),
                ('end', models.SmallIntegerField(choices=[(1, '8'), (2, '8:30'), (3, '9'), (4, '9:30'), (5, '10'), (6, '10:30'), (7, '11'), (8, '11:30'), (9, '12'), (10, '12:30'), (11, '13'), (12, '13:30'), (13, '14'), (14, '14:30'), (15, '15'), (16, '15:30'), (17, '16'), (18, '16:30'), (19, '17'), (20, '17:30'), (21, '18'), (22, '18:30'), (23, '19'), (24, '19:30'), (25, '20'), (26, '20:30'), (27, '21'), (28, '21:30')], verbose_name='End')),
                ('order', models.SmallIntegerField(blank=True, verbose_name='Order')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
