# Generated by Django 3.2.5 on 2022-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0002_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='end',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='start',
        ),
        migrations.AddField(
            model_name='opening',
            name='str_schedule',
            field=models.CharField(max_length=36, null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
