# Generated by Django 3.2.11 on 2023-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0003_rename_schedule_schedulerange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='str_schedules',
            new_name='range_schedules',
        ),
        migrations.AlterField(
            model_name='opening',
            name='day',
            field=models.SmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], error_messages={'unique': 'This day already exists.'}, unique=True),
        ),
    ]
