# Generated by Django 3.2.5 on 2022-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0003_auto_20220104_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='str_schedule',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Schedule'),
        ),
    ]
