# Generated by Django 3.2.5 on 2022-01-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0007_alter_opening_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.CharField(choices=[('8', '8'), ('8:30', '8:30'), ('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30'), ('13', '13'), ('13:30', '13:30'), ('14', '14'), ('14:30', '14:30'), ('15', '15'), ('15:30', '15:30'), ('16', '16'), ('16:30', '16:30'), ('17', '17'), ('17:30', '17:30'), ('18', '18'), ('18:30', '18:30'), ('19', '19'), ('19:30', '19:30'), ('20', '20'), ('20:30', '20:30'), ('21', '21'), ('21:30', '21:30')], max_length=5, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='opening.opening'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.CharField(choices=[('8', '8'), ('8:30', '8:30'), ('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30'), ('13', '13'), ('13:30', '13:30'), ('14', '14'), ('14:30', '14:30'), ('15', '15'), ('15:30', '15:30'), ('16', '16'), ('16:30', '16:30'), ('17', '17'), ('17:30', '17:30'), ('18', '18'), ('18:30', '18:30'), ('19', '19'), ('19:30', '19:30'), ('20', '20'), ('20:30', '20:30'), ('21', '21'), ('21:30', '21:30')], max_length=5, verbose_name='Start'),
        ),
    ]
