# Generated by Django 3.2.5 on 2022-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0009_auto_20220104_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='day',
            field=models.SmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], unique=True, verbose_name='Day'),
        ),
    ]
