# Generated by Django 3.2.5 on 2022-01-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0010_alter_opening_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='closed',
        ),
        migrations.AddField(
            model_name='opening',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='day',
            field=models.SmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], error_messages={'unique': 'Ya existe este día.'}, unique=True, verbose_name='Day'),
        ),
    ]
