# Generated by Django 3.2.5 on 2021-10-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Phone')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Contact date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_information.userinformation', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact List',
                'ordering': ['-date'],
            },
        ),
    ]
