# Generated by Django 3.2.11 on 2023-05-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0002_auto_20230508_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScheduleRange',
        ),
    ]
