# Generated by Django 3.2.11 on 2023-05-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0004_auto_20230508_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='range_schedules',
        ),
        migrations.AddField(
            model_name='opening',
            name='schedule_range',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
