# Generated by Django 3.2.11 on 2023-10-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0006_auto_20231009_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerange',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedulerange',
            name='order',
        ),
        migrations.RemoveField(
            model_name='schedulerange',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='schedulerange',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedulerange',
            name='start',
            field=models.TimeField(),
        ),
    ]
