# Generated by Django 3.2.11 on 2023-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0007_auto_20231009_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='week_day',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opening',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], error_messages={'unique': 'This day already exists.'}, unique=True),
        ),
    ]
