# Generated by Django 3.2.11 on 2023-10-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0008_auto_20231009_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='week_day',
            new_name='weekday',
        ),
    ]
