# Generated by Django 3.2.5 on 2022-01-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('contactInformation', models.TextField(verbose_name='Informacion de contacto')),
                ('averageLeadTime', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Tiempo de entrega promedio (en dias)')),
                ('maxLeadTime', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Tiempo de entrega maximo  (en dias)')),
                ('minLeadTime', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Tiempo de entrega minimo  (en dias)')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='LeadTimeVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadTime', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Tiempo de entrega (en dias)')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Tiempo de entrega',
                'verbose_name_plural': 'Tiempos de entrega',
            },
        ),
    ]
