# Generated by Django 3.2.5 on 2022-01-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadtimevendors',
            old_name='leadTime',
            new_name='lead_time',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='averageLeadTime',
            new_name='average_lead_time',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='contactInformation',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='maxLeadTime',
            new_name='max_lead_time',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='minLeadTime',
            new_name='min_lead_time',
        ),
    ]
