# Generated by Django 3.2.5 on 2022-01-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20220117_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadtimevendors',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='vendors.vendor'),
        ),
    ]
